name: Publish on Docker Hub

on:
  release:
    types: [published]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: coverage run application/tests.py
      - name: Tests report
        run: coverage report

  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_PROJECT }}
    steps:
      - uses: actions/checkout@master
      - name: Login to docker.io
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zet694/github_ci_cd
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}